// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var $$Option = { };

var Select = {
  $$Option: $$Option
};

var Input = { };

var Item = { };

var SubMenu = { };

var ItemGroup = { };

var Menu = {
  Item: Item,
  SubMenu: SubMenu,
  ItemGroup: ItemGroup
};

var Modal = { };

var Column = { };

var ColumnGroup = { };

var Table = {
  Column: Column,
  ColumnGroup: ColumnGroup
};

export {
  Select ,
  Input ,
  Menu ,
  Modal ,
  Table ,
  
}
/* No side effect */
