// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


var $$Option = /* module */[];

var Select = /* module */[/* Option */$$Option];

var Input = /* module */[];

var Item = /* module */[];

var SubMenu = /* module */[];

var ItemGroup = /* module */[];

var Menu = /* module */[
  /* Item */Item,
  /* SubMenu */SubMenu,
  /* ItemGroup */ItemGroup
];

var Table = /* module */[];

export {
  Select ,
  Input ,
  Menu ,
  Table ,
  
}
/* No side effect */
