// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function toolbarToJs(param) {
  return {
          h1: param.h1,
          h2: param.h2,
          h3: param.h3,
          h4: param.h4,
          img: param.img,
          link: param.link,
          code: param.code,
          preview: param.preview,
          expand: param.expand,
          undo: param.undo,
          redo: param.redo,
          save: param.save,
          subfield: param.subfield
        };
}

function toolbarFromJs(param) {
  return {
          h1: param.h1,
          h2: param.h2,
          h3: param.h3,
          h4: param.h4,
          img: param.img,
          link: param.link,
          code: param.code,
          preview: param.preview,
          expand: param.expand,
          undo: param.undo,
          redo: param.redo,
          save: param.save,
          subfield: param.subfield
        };
}

var defaultOption = toolbarToJs({
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      img: true,
      link: true,
      code: true,
      preview: true,
      expand: true,
      undo: false,
      redo: false,
      save: false,
      subfield: true
    });

export {
  toolbarToJs ,
  toolbarFromJs ,
  defaultOption ,
  
}
/* defaultOption Not a pure module */
