// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


function toolbarToJs(param) {
  return {
          h1: param[/* h1 */0],
          h2: param[/* h2 */1],
          h3: param[/* h3 */2],
          h4: param[/* h4 */3],
          img: param[/* img */4],
          link: param[/* link */5],
          code: param[/* code */6],
          preview: param[/* preview */7],
          expand: param[/* expand */8],
          undo: param[/* undo */9],
          redo: param[/* redo */10],
          save: param[/* save */11],
          subfield: param[/* subfield */12]
        };
}

function toolbarFromJs(param) {
  return /* record */[
          /* h1 */param.h1,
          /* h2 */param.h2,
          /* h3 */param.h3,
          /* h4 */param.h4,
          /* img */param.img,
          /* link */param.link,
          /* code */param.code,
          /* preview */param.preview,
          /* expand */param.expand,
          /* undo */param.undo,
          /* redo */param.redo,
          /* save */param.save,
          /* subfield */param.subfield
        ];
}

var defaultOption = toolbarToJs(/* record */[
      /* h1 */true,
      /* h2 */true,
      /* h3 */true,
      /* h4 */true,
      /* img */true,
      /* link */true,
      /* code */true,
      /* preview */true,
      /* expand */true,
      /* undo */false,
      /* redo */false,
      /* save */false,
      /* subfield */true
    ]);

var Editor = /* module */[];

export {
  toolbarToJs ,
  toolbarFromJs ,
  defaultOption ,
  Editor ,
  
}
/* defaultOption Not a pure module */
