// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


var Table = /* module */[];

var TableBody = /* module */[];

var TableFooter = /* module */[];

var TableHead = /* module */[];

var TableRow = /* module */[];

var TableCell = /* module */[];

export {
  Table ,
  TableBody ,
  TableFooter ,
  TableHead ,
  TableRow ,
  TableCell ,
  
}
/* No side effect */
