// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Table = { };

var TableBody = { };

var TableFooter = { };

var TableHead = { };

var TableRow = { };

var TableCell = { };

export {
  Table ,
  TableBody ,
  TableFooter ,
  TableHead ,
  TableRow ,
  TableCell ,
  
}
/* No side effect */
