// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function CardsList(Props) {
  return React.createElement("div", undefined, "Cards Page");
}

var make = CardsList;

export {
  make ,
  
}
/* react Not a pure module */
