// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as List$ReactHooksTemplate from "../components/List.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";

function ExamsList(Props) {
  return React.createElement("div", undefined, React.createElement(List$ReactHooksTemplate.make, {
                  query: Queries$ReactHooksTemplate.ListExams.make
                }));
}

var make = ExamsList;

export {
  make ,
  
}
/* react Not a pure module */
