// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function ExamsList(Props) {
  return React.createElement("div", undefined, "Exam Page");
}

var make = ExamsList;

export {
  make ,
  
}
/* react Not a pure module */
