// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Antd from "antd";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as Utils$ReactHooksTemplate from "../Utils.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";

var testData = /* array */[
  {
    id: "1",
    question: "Mike",
    rationale: "10 Downing Street"
  },
  {
    id: "2",
    question: "John",
    rationale: "10 Downing Street"
  }
];

var columnHeads = /* array */[
  {
    title: "Question",
    dataIndex: "question",
    key: "question"
  },
  {
    title: "Rationale",
    dataIndex: "rationale",
    key: "rationale"
  }
];

function ExamPage(Props) {
  var id = Props.id;
  var request = Queries$ReactHooksTemplate.GetExam.make(id, /* () */0);
  var match = Curry._5(ReasonUrql.Hooks.useQuery, request, undefined, undefined, undefined, /* () */0);
  var response = match[0].response;
  if (typeof response === "number") {
    if (response === /* Fetching */0) {
      return Utils$ReactHooksTemplate.str("Fetching");
    } else {
      return Utils$ReactHooksTemplate.str("No Data");
    }
  } else if (response.tag) {
    return Utils$ReactHooksTemplate.str("Error");
  } else {
    var match$1 = response[0].getExam;
    if (match$1 !== undefined) {
      var data = match$1;
      var examType = Queries$ReactHooksTemplate.stringifyExamType(data.type_);
      console.log(data);
      return React.createElement(React.Fragment, undefined, React.createElement("div", {
                      className: "text-4xl font-semibold text-indigo-800"
                    }, Utils$ReactHooksTemplate.str(data.name)), React.createElement("div", {
                      className: "text-xl text-indigo-800"
                    }, Utils$ReactHooksTemplate.str(examType)), React.createElement("div", {
                      className: "mt-6"
                    }, React.createElement("div", {
                          className: "flex justify-between items-center"
                        }, React.createElement("button", {
                              className: "p-2 bg-indigo-800 text-blue-100 rounded-lg"
                            }, Utils$ReactHooksTemplate.str("+ Add Card"))), React.createElement(Antd.Table, {
                          columns: columnHeads,
                          dataSource: testData
                        })));
    } else {
      return Utils$ReactHooksTemplate.str("No Exams. Create one First");
    }
  }
}

var make = ExamPage;

export {
  testData ,
  columnHeads ,
  make ,
  
}
/* antd Not a pure module */
