// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function ExamPage(Props) {
  Props.id;
  return React.createElement("div", undefined, "Exam Page");
}

var make = ExamPage;

export {
  make ,
  
}
/* react Not a pure module */
