// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as Table$ReactHooksTemplate from "../components/Table.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";

function str(prim) {
  return prim;
}

function Home(Props) {
  var request = Queries$ReactHooksTemplate.ListModules.make(/* () */0);
  var match = Curry._5(ReasonUrql.Hooks.useQuery, request, undefined, undefined, undefined, /* () */0);
  var response = match[0].response;
  if (typeof response === "number") {
    if (response === /* Fetching */0) {
      return "Fetching";
    } else {
      return "No Data";
    }
  } else if (response.tag) {
    return "Error";
  } else {
    var match$1 = response[0].modules;
    if (match$1 !== undefined) {
      return React.createElement(React.Fragment, undefined, React.createElement("div", {
                      className: "flex justify-between items-start"
                    }, React.createElement("p", {
                          className: "font-bold text-4xl mb-8"
                        }, "Modules")), React.createElement(Table$ReactHooksTemplate.make, {
                      items: match$1,
                      entity: /* Module */0
                    }));
    } else {
      return "No items";
    }
  }
}

var make = Home;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
