// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function str(prim) {
  return prim;
}

function Home(Props) {
  var goToNote = function (_event) {
    return ReasonReactRouter.push("/notes");
  };
  return React.createElement("div", undefined, React.createElement("div", undefined, "Home Page"), React.createElement("button", {
                  onClick: goToNote
                }, "Make new note"));
}

var make = Home;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
