// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Link$ReactHooksTemplate from "../components/Link.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";

function str(prim) {
  return prim;
}

function ModulePage(Props) {
  var id = Props.id;
  var request = Queries$ReactHooksTemplate.GetModule[/* make */3](id, /* () */0);
  var match = Curry._4(ReasonUrql.Hooks[/* useQuery */1], request, undefined, undefined, /* () */0);
  var response = match[0][/* response */3];
  if (typeof response === "number") {
    if (response === 0) {
      return "Fetching";
    } else {
      return "No Data";
    }
  } else if (response.tag) {
    return "Error";
  } else {
    var match$1 = response[0].module_;
    if (match$1 !== undefined) {
      var module_ = Caml_option.valFromOption(match$1);
      var match$2 = module_.name;
      var match$3 = module_.description;
      var match$4 = module_.subjects;
      if (match$2 !== undefined && match$3 !== undefined && match$4 !== undefined) {
        var subjectsList = $$Array.map((function (subject) {
                if (subject !== undefined) {
                  var subject$1 = Caml_option.valFromOption(subject);
                  var match = subject$1.id;
                  var match$1 = subject$1.name;
                  if (match !== undefined && match$1 !== undefined) {
                    var id = match;
                    return React.createElement(Link$ReactHooksTemplate.make, {
                                to_: "subjects/" + (String(id) + ""),
                                children: React.createElement("div", {
                                      className: "text-indigo-900 cursor-pointer hover:text-purple-600"
                                    }, match$1),
                                key: id
                              });
                  } else {
                    return null;
                  }
                } else {
                  return "No Subject";
                }
              }), match$4);
        return React.createElement("div", undefined, React.createElement("div", {
                        className: "text-4xl font-semibold text-indigo-800"
                      }, match$2), React.createElement("div", {
                        className: "text-lg font-semibold text-indigo-600"
                      }, match$3), React.createElement("div", {
                        className: "mt-6"
                      }, React.createElement("div", {
                            className: "text-lg"
                          }, "Subjects:"), React.createElement("div", undefined, subjectsList)));
      } else {
        return null;
      }
    } else {
      return "No Item";
    }
  }
}

var make = ModulePage;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
