// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function ModulePage(Props) {
  Props.id;
  return React.createElement("div", undefined, "Module Page");
}

var make = ModulePage;

export {
  make ,
  
}
/* react Not a pure module */
