// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Utils$ReactHooksTemplate from "../Utils.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";
import * as NoteEdit$ReactHooksTemplate from "../components/NoteEdit.bs.js";

var Markdown = { };

function Note(Props) {
  var id = Props.id;
  var request = Queries$ReactHooksTemplate.GetNote.make(id, /* () */0);
  var match = Curry._5(ReasonUrql.Hooks.useQuery, request, undefined, undefined, undefined, /* () */0);
  var response = match[0].response;
  if (typeof response === "number") {
    if (response === /* Fetching */0) {
      return Utils$ReactHooksTemplate.str("Fetchin");
    } else {
      return Utils$ReactHooksTemplate.str("No Data");
    }
  } else if (response.tag) {
    return Utils$ReactHooksTemplate.str("Error");
  } else {
    var match$1 = response[0].note;
    if (match$1 !== undefined) {
      var note = Caml_option.valFromOption(match$1);
      var name = Belt_Option.mapWithDefault(note.name, "Missing name", (function (txt) {
              return txt;
            }));
      var content = Belt_Option.mapWithDefault(note.content, "Missing name", (function (txt) {
              return txt;
            }));
      var pageId = Belt_Option.mapWithDefault(note.pageId, "", (function (txt) {
              return txt;
            }));
      return React.createElement("div", undefined, React.createElement("div", undefined, React.createElement(NoteEdit$ReactHooksTemplate.make, {
                          content: content,
                          id: id,
                          pageId: pageId,
                          name: name
                        })));
    } else {
      return Utils$ReactHooksTemplate.str("No Note");
    }
  }
}

var make = Note;

export {
  Markdown ,
  make ,
  
}
/* react Not a pure module */
