// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Antd from "antd";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as ForEditor from "for-editor";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Utils$ReactHooksTemplate from "../Utils.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";
import * as ForEditor$ReactHooksTemplate from "../bindings/ForEditor.bs.js";
import * as Mutations$ReactHooksTemplate from "../graphql/Mutations.bs.js";

function NotesForm(Props) {
  var topicIdProp = Props.topicIdProp;
  var pageIdProp = Props.pageIdProp;
  var match = React.useState((function () {
          return "";
        }));
  var setName = match[1];
  var name = match[0];
  var match$1 = React.useState((function () {
          return topicIdProp;
        }));
  var setTopicId = match$1[1];
  var topicId = match$1[0];
  var match$2 = React.useState((function () {
          return pageIdProp;
        }));
  var setPageId = match$2[1];
  var pageId = match$2[0];
  var match$3 = React.useState((function () {
          return "";
        }));
  var setDescription = match$3[1];
  var description = match$3[0];
  var match$4 = React.useState((function () {
          return "";
        }));
  var content = match$4[0];
  var topicsListRequest = Queries$ReactHooksTemplate.ListTopics[/* make */3](/* () */0);
  var match$5 = Curry._4(ReasonUrql.Hooks[/* useQuery */1], topicsListRequest, undefined, undefined, /* () */0);
  var topicsListQueryResponse = match$5[0][/* response */3];
  var topicQuery = Queries$ReactHooksTemplate.GetTopic[/* make */3](topicId, /* () */0);
  var match$6 = Curry._4(ReasonUrql.Hooks[/* useQuery */1], topicQuery, undefined, undefined, /* () */0);
  var topicQueryResponse = match$6[0][/* response */3];
  var mutation = Mutations$ReactHooksTemplate.CreateNote[/* make */3](name, pageId, description, content, /* () */0);
  var match$7 = Curry._1(ReasonUrql.Hooks[/* useMutation */0], mutation);
  var executeMutation = match$7[1];
  var topicsSelect;
  if (typeof topicsListQueryResponse === "number") {
    topicsSelect = topicsListQueryResponse === 0 ? Utils$ReactHooksTemplate.str("Loading") : Utils$ReactHooksTemplate.str("Not Found");
  } else if (topicsListQueryResponse.tag) {
    topicsSelect = Utils$ReactHooksTemplate.str("Error");
  } else {
    var topics = Belt_Array.map(Belt_Option.getWithDefault(topicsListQueryResponse[0].topics, /* array */[]), (function (topic) {
            return Belt_Option.mapWithDefault(topic, null, (function (topic) {
                          var id = Belt_Option.mapWithDefault(topic.id, "Missing description", (function (txt) {
                                  return txt;
                                }));
                          var name = Belt_Option.mapWithDefault(topic.name, "Missing description", (function (txt) {
                                  return txt;
                                }));
                          return React.createElement(Antd.Select.Option, {
                                      key: id,
                                      value: id,
                                      children: Utils$ReactHooksTemplate.str(name)
                                    });
                        }));
          }));
    topicsSelect = React.createElement(Antd.Select, {
          className: "w-full",
          value: topicId,
          onSelect: (function (value) {
              Curry._1(setTopicId, (function (param) {
                      return value;
                    }));
              return Curry._1(setPageId, (function (param) {
                            return "";
                          }));
            }),
          children: topics
        });
  }
  var pageSelect;
  if (typeof topicQueryResponse === "number") {
    pageSelect = topicQueryResponse === 0 ? Utils$ReactHooksTemplate.str("Loading") : Utils$ReactHooksTemplate.str("Not Found");
  } else if (topicQueryResponse.tag) {
    pageSelect = React.createElement("div", undefined, Utils$ReactHooksTemplate.str("Please Select a subject"));
  } else {
    var pages = Belt_Array.map(Belt_Option.getWithDefault(Belt_Option.flatMap(topicQueryResponse[0].topic, (function (topic) {
                    return topic.pages;
                  })), /* array */[]), (function (pages) {
            return Belt_Option.mapWithDefault(pages, null, (function (pages) {
                          var id = Belt_Option.mapWithDefault(pages.id, "Missing id", (function (txt) {
                                  return txt;
                                }));
                          var name = Belt_Option.mapWithDefault(pages.name, "Missing name", (function (txt) {
                                  return txt;
                                }));
                          return React.createElement(Antd.Select.Option, {
                                      key: id,
                                      value: id,
                                      children: Utils$ReactHooksTemplate.str(name)
                                    });
                        }));
          }));
    pageSelect = React.createElement(Antd.Select, {
          className: "w-full",
          value: pageId,
          onSelect: (function (value) {
              return Curry._1(setPageId, (function (param) {
                            return value;
                          }));
            }),
          children: pages
        });
  }
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "text-xl font-bold pb-3"
                }, Utils$ReactHooksTemplate.str("Create Note")), React.createElement("div", {
                  className: "flex flex-row"
                }, React.createElement("div", {
                      className: "flex-1 pr-2"
                    }, React.createElement("label", undefined, Utils$ReactHooksTemplate.str("Select Topic"), topicsSelect)), React.createElement("div", {
                      className: "flex-1 pr-2"
                    }, React.createElement("label", undefined, Utils$ReactHooksTemplate.str("Select Page"), pageSelect))), React.createElement("div", {
                  className: "mt-3"
                }, React.createElement("label", undefined, Utils$ReactHooksTemplate.str("Name"), React.createElement(Antd.Input, {
                          value: name,
                          onChange: (function ($$event) {
                              return Curry._1(setName, $$event.target.value);
                            })
                        }))), React.createElement("div", {
                  className: "mt-3"
                }, React.createElement("label", undefined, Utils$ReactHooksTemplate.str("Description"), React.createElement(Antd.Input, {
                          value: description,
                          onChange: (function ($$event) {
                              return Curry._1(setDescription, $$event.target.value);
                            })
                        }))), React.createElement("div", {
                  className: "mt-3 markdown"
                }, React.createElement(ForEditor.default, {
                      value: content,
                      onChange: match$4[1],
                      language: "en",
                      toolbar: ForEditor$ReactHooksTemplate.defaultOption
                    })), React.createElement("div", {
                  className: "mt-4"
                }, React.createElement("button", {
                      className: "rounded-sm px-3 py-2 bg-red-500 text-white rounded-lg mr-5",
                      onClick: (function (param) {
                          return Utils$ReactHooksTemplate.push("/subjects");
                        })
                    }, Utils$ReactHooksTemplate.str("Cancel")), React.createElement("button", {
                      className: "rounded-sm px-3 py-2 bg-green-500 text-white rounded-lg",
                      onClick: (function (param) {
                          Curry._1(executeMutation, /* () */0);
                          return /* () */0;
                        })
                    }, Utils$ReactHooksTemplate.str("Save"))));
}

var make = NotesForm;

export {
  make ,
  
}
/* antd Not a pure module */
