// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as List$ReactHooksTemplate from "../components/List.bs.js";
import * as Utils$ReactHooksTemplate from "../Utils.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";

function str(prim) {
  return prim;
}

function SubjectsList(Props) {
  var request = Queries$ReactHooksTemplate.ListSubjects[/* make */3](/* () */0);
  var match = Curry._4(ReasonUrql.Hooks[/* useQuery */1], request, undefined, undefined, /* () */0);
  var response = match[0][/* response */3];
  if (typeof response === "number") {
    if (response === 0) {
      return "Fetching";
    } else {
      return "No Data";
    }
  } else if (response.tag) {
    return "Error";
  } else {
    var match$1 = response[0].subjects;
    if (match$1 !== undefined) {
      return React.createElement(React.Fragment, undefined, React.createElement("div", {
                      className: "flex justify-between items-start"
                    }, React.createElement("p", {
                          className: "font-bold text-4xl mb-8"
                        }, "Subjects"), React.createElement("button", {
                          className: "p-2 bg-indigo-800 text-blue-100 rounded-lg",
                          onClick: (function (param) {
                              return Utils$ReactHooksTemplate.push("/subjects/create");
                            })
                        }, "+ Create Subject")), React.createElement(List$ReactHooksTemplate.make, {
                      items: match$1,
                      entity: /* Subject */1
                    }));
    } else {
      return "No items";
    }
  }
}

var make = SubjectsList;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
