// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as Utils$ReactHooksTemplate from "../Utils.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";
import * as EditSubjectForm$ReactHooksTemplate from "../components/EditSubjectForm.bs.js";

function SubjectPage(Props) {
  var id = Props.id;
  var request = Queries$ReactHooksTemplate.GetSubject[/* make */3](id, /* () */0);
  var match = Curry._4(ReasonUrql.Hooks[/* useQuery */1], request, undefined, undefined, /* () */0);
  var response = match[0][/* response */3];
  if (typeof response === "number") {
    if (response === 0) {
      return Utils$ReactHooksTemplate.str("Fetching");
    } else {
      return Utils$ReactHooksTemplate.str("No Data");
    }
  } else if (response.tag) {
    return Utils$ReactHooksTemplate.str("Error");
  } else {
    var match$1 = response[0].subject;
    if (match$1 !== undefined) {
      var subject = Caml_option.valFromOption(match$1);
      var subjectDescription = Belt_Option.mapWithDefault(subject.description, "Missing description", (function (txt) {
              return txt;
            }));
      var subjectName = Belt_Option.mapWithDefault(subject.name, "Missing name", (function (txt) {
              return txt;
            }));
      var parentId = Belt_Option.mapWithDefault(subject.moduleId, "", (function (txt) {
              return txt;
            }));
      var topicsList = $$Array.map((function (topic) {
              if (topic !== undefined) {
                var topic$1 = Caml_option.valFromOption(topic);
                var topicId = Belt_Option.mapWithDefault(topic$1.id, "Missing id", (function (txt) {
                        return txt;
                      }));
                var topicName = Belt_Option.mapWithDefault(topic$1.name, "Missing name", (function (txt) {
                        return txt;
                      }));
                var topicDescription = Belt_Option.mapWithDefault(topic$1.description, "Missing description", (function (txt) {
                        return txt;
                      }));
                return React.createElement(Core.TableRow, {
                            children: null,
                            key: topicId
                          }, React.createElement(Core.TableCell, {
                                children: React.createElement("button", {
                                      onClick: (function (param) {
                                          return Utils$ReactHooksTemplate.push("/topics/" + (String(topicId) + ""));
                                        })
                                    }, React.createElement("div", {
                                          className: "text-indigo-900 cursor-pointer hover:text-purple-600"
                                        }, Utils$ReactHooksTemplate.str(topicId)))
                              }), React.createElement(Core.TableCell, {
                                children: React.createElement("button", {
                                      onClick: (function (param) {
                                          return Utils$ReactHooksTemplate.push("/topics/" + (String(topicId) + ""));
                                        })
                                    }, React.createElement("div", {
                                          className: "text-indigo-900 cursor-pointer hover:text-purple-600"
                                        }, Utils$ReactHooksTemplate.str(topicName)))
                              }), React.createElement(Core.TableCell, {
                                children: Utils$ReactHooksTemplate.str(topicDescription)
                              }));
              } else {
                return Utils$ReactHooksTemplate.str("No item");
              }
            }), Belt_Option.getWithDefault(subject.topics, /* array */[]));
      return React.createElement(React.Fragment, undefined, React.createElement("div", {
                      className: "flex justify-between"
                    }, React.createElement(EditSubjectForm$ReactHooksTemplate.make, {
                          id: id,
                          name: subjectName,
                          description: subjectDescription
                        })), React.createElement("div", {
                      className: "mt-6"
                    }, React.createElement("div", {
                          className: "flex justify-between items-center"
                        }, React.createElement("div", {
                              className: "text-lg"
                            }, Utils$ReactHooksTemplate.str("Topics:")), React.createElement("button", {
                              className: "p-2 bg-indigo-800 text-blue-100 rounded-lg",
                              onClick: (function (param) {
                                  return Utils$ReactHooksTemplate.push("/modules/" + (String(parentId) + ("/subjects/" + (String(id) + "/topics/create"))));
                                })
                            }, Utils$ReactHooksTemplate.str("+ Create Topic"))), React.createElement(Core.Table, {
                          children: null
                        }, React.createElement(Core.TableHead, {
                              children: React.createElement(Core.TableRow, {
                                    children: null
                                  }, React.createElement(Core.TableCell, {
                                        children: Utils$ReactHooksTemplate.str("ID")
                                      }), React.createElement(Core.TableCell, {
                                        children: Utils$ReactHooksTemplate.str("Name")
                                      }), React.createElement(Core.TableCell, {
                                        children: Utils$ReactHooksTemplate.str("Description")
                                      }))
                            }), React.createElement(Core.TableBody, {
                              children: topicsList
                            }))));
    } else {
      return Utils$ReactHooksTemplate.str("No Subject");
    }
  }
}

var make = SubjectPage;

export {
  make ,
  
}
/* react Not a pure module */
