// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as Utils$ReactHooksTemplate from "../Utils.bs.js";
import * as Queries$ReactHooksTemplate from "../graphql/Queries.bs.js";
import * as EditTopicForm$ReactHooksTemplate from "../components/EditTopicForm.bs.js";

function TopicPage(Props) {
  var id = Props.id;
  var request = Queries$ReactHooksTemplate.GetTopic.make(id, /* () */0);
  var match = Curry._5(ReasonUrql.Hooks.useQuery, request, undefined, undefined, undefined, /* () */0);
  var response = match[0].response;
  if (typeof response === "number") {
    if (response === /* Fetching */0) {
      return Utils$ReactHooksTemplate.str("Fetching");
    } else {
      return Utils$ReactHooksTemplate.str("No Data");
    }
  } else if (response.tag) {
    return Utils$ReactHooksTemplate.str("Error");
  } else {
    var match$1 = response[0].topic;
    if (match$1 !== undefined) {
      var topic = Caml_option.valFromOption(match$1);
      var topicDescription = Belt_Option.mapWithDefault(topic.description, "Missing description", (function (txt) {
              return txt;
            }));
      var topicName = Belt_Option.mapWithDefault(topic.name, "Missing name", (function (txt) {
              return txt;
            }));
      var parentId = Belt_Option.mapWithDefault(topic.subjectId, "Missing description", (function (txt) {
              return txt;
            }));
      var pagesList = $$Array.map((function (page) {
              if (page !== undefined) {
                var page$1 = Caml_option.valFromOption(page);
                var pageId = Belt_Option.mapWithDefault(page$1.id, "Missing id", (function (txt) {
                        return txt;
                      }));
                var topicName = Belt_Option.mapWithDefault(page$1.name, "Missing name", (function (txt) {
                        return txt;
                      }));
                var topicDescription = Belt_Option.mapWithDefault(page$1.description, "Missing description", (function (txt) {
                        return txt;
                      }));
                return React.createElement(Core.TableRow, {
                            children: null,
                            key: pageId
                          }, React.createElement(Core.TableCell, {
                                children: React.createElement("button", {
                                      onClick: (function (param) {
                                          return Utils$ReactHooksTemplate.push("/pages/" + (String(pageId) + ""));
                                        })
                                    }, React.createElement("div", {
                                          className: "text-indigo-900 cursor-pointer hover:text-purple-600"
                                        }, Utils$ReactHooksTemplate.str(pageId)))
                              }), React.createElement(Core.TableCell, {
                                children: React.createElement("button", {
                                      onClick: (function (param) {
                                          return Utils$ReactHooksTemplate.push("/pages/" + (String(pageId) + ""));
                                        })
                                    }, React.createElement("div", {
                                          className: "text-indigo-900 cursor-pointer hover:text-purple-600"
                                        }, Utils$ReactHooksTemplate.str(topicName)))
                              }), React.createElement(Core.TableCell, {
                                children: Utils$ReactHooksTemplate.str(topicDescription)
                              }));
              } else {
                return Utils$ReactHooksTemplate.str("No item");
              }
            }), Belt_Option.getWithDefault(topic.pages, /* array */[]));
      return React.createElement(React.Fragment, undefined, React.createElement("div", {
                      className: "flex justify-between"
                    }, React.createElement(EditTopicForm$ReactHooksTemplate.make, {
                          id: id,
                          name: topicName,
                          description: topicDescription
                        })), React.createElement("div", {
                      className: "mt-6"
                    }, React.createElement("div", {
                          className: "flex justify-between items-center"
                        }, React.createElement("div", {
                              className: "text-lg"
                            }, Utils$ReactHooksTemplate.str("Pages:")), React.createElement("button", {
                              className: "p-2 bg-indigo-800 text-blue-100 rounded-lg",
                              onClick: (function (param) {
                                  return Utils$ReactHooksTemplate.push("/subjects/" + (String(parentId) + ("/topics/" + (String(id) + "/pages/create"))));
                                })
                            }, Utils$ReactHooksTemplate.str("+ Create Page"))), React.createElement(Core.Table, {
                          children: null
                        }, React.createElement(Core.TableHead, {
                              children: React.createElement(Core.TableRow, {
                                    children: null
                                  }, React.createElement(Core.TableCell, {
                                        children: Utils$ReactHooksTemplate.str("ID")
                                      }), React.createElement(Core.TableCell, {
                                        children: Utils$ReactHooksTemplate.str("Name")
                                      }), React.createElement(Core.TableCell, {
                                        children: Utils$ReactHooksTemplate.str("Description")
                                      }))
                            }), React.createElement(Core.TableBody, {
                              children: pagesList
                            }))));
    } else {
      return Utils$ReactHooksTemplate.str("No topic");
    }
  }
}

var make = TopicPage;

export {
  make ,
  
}
/* react Not a pure module */
