// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Antd from "antd";
import * as React from "react";

function CategorySelect(Props) {
  return React.createElement("div", undefined, React.createElement(Antd.Select, {
                  className: "w-full",
                  children: React.createElement(Antd.Select.Option, {
                        key: "1",
                        value: "1",
                        children: "Heere"
                      })
                }));
}

var make = CategorySelect;

export {
  make ,
  
}
/* antd Not a pure module */
