// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$ReactHooksTemplate from "./Link.bs.js";

function str(prim) {
  return prim;
}

function Header(Props) {
  return React.createElement("header", undefined, React.createElement(Link$ReactHooksTemplate.make, {
                  to_: "/",
                  children: "Reviewer Admin"
                }), React.createElement("nav", undefined, "Hello User"));
}

var make = Header;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
