// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$ReactHooksTemplate from "./Link.bs.js";

function str(prim) {
  return prim;
}

import styled from "@emotion/styled"
;

import css from "@styled-system/css"
;

var header = (
      styled.div(css({
        border: "1px solid #e2e2e2",
        p: 3,
        display: "flex",
        justifyContent: "space-between"
      }))
    );

function Header$HeaderContainer(Props) {
  var children = Props.children;
  return React.createElement(header, {
              children: children
            });
}

var HeaderContainer = /* module */[
  /* header */header,
  /* make */Header$HeaderContainer
];

function Header(Props) {
  return React.createElement(Header$HeaderContainer, {
              children: null
            }, React.createElement(Link$ReactHooksTemplate.make, {
                  to_: "/",
                  children: "Reviewer Admin"
                }), React.createElement("nav", undefined, "Hello User"));
}

var make = Header;

export {
  str ,
  HeaderContainer ,
  make ,
  
}
/*  Not a pure module */
