// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$ReactHooksTemplate from "./Link.bs.js";

function str(prim) {
  return prim;
}

function ItemCard(Props) {
  var name = Props.name;
  var id = Props.id;
  var entity = Props.entity;
  var entityString;
  switch (entity) {
    case 0 : 
        entityString = "modules";
        break;
    case 1 : 
        entityString = "subjects";
        break;
    case 2 : 
        entityString = "topics";
        break;
    case 3 : 
        entityString = "pages";
        break;
    case 4 : 
        entityString = "notes";
        break;
    
  }
  var link = "/" + (String(entityString) + ("/" + (String(id) + "")));
  return React.createElement(Link$ReactHooksTemplate.make, {
              to_: link,
              children: React.createElement("div", {
                    className: "cursor-pointer text-indigo-900 hover:text-indigo-500 text-lg mb-3"
                  }, name)
            });
}

var make = ItemCard;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
