// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Link(Props) {
  var to_ = Props.to_;
  var children = Props.children;
  var handleClick = function (_e) {
    return ReasonReactRouter.push(to_);
  };
  return React.createElement("a", {
              onClick: handleClick
            }, children);
}

var make = Link;

export {
  make ,
  
}
/* react Not a pure module */
