// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Module(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, name);
}

var make = Module;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
