// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Module$ReactHooksTemplate from "./Module.bs.js";

function str(prim) {
  return prim;
}

function ModulesList(Props) {
  var modules = Props.modules;
  var modulesList = $$Array.map((function (module_) {
          if (module_ !== undefined) {
            var module_$1 = Caml_option.valFromOption(module_);
            var match = module_$1.name;
            var match$1 = module_$1.id;
            if (match !== undefined && match$1 !== undefined) {
              return React.createElement(Module$ReactHooksTemplate.make, {
                          name: match,
                          key: match$1
                        });
            } else {
              return "No Name";
            }
          } else {
            return "None";
          }
        }), modules);
  return React.createElement("div", undefined, modulesList);
}

var make = ModulesList;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
