// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Antd from "antd";
import * as React from "react";
import * as Utils$ReactHooksTemplate from "../Utils.bs.js";

function Sidebar$SidebarLink(Props) {
  var children = Props.children;
  var to_ = Props.to_;
  return React.createElement("a", {
              onClick: (function (_e) {
                  return Utils$ReactHooksTemplate.push(to_);
                })
            }, children);
}

var SidebarLink = {
  make: Sidebar$SidebarLink
};

function Sidebar(Props) {
  return React.createElement("div", undefined, React.createElement(Antd.Menu, {
                  defaultOpenKeys: /* array */[
                    "sub1",
                    "sub2"
                  ],
                  mode: "inline",
                  children: null
                }, React.createElement(Antd.Menu.SubMenu, {
                      children: null,
                      key: "sub1",
                      title: "Lectures"
                    }, React.createElement(Antd.Menu.Item, {
                          key: "1",
                          children: React.createElement(Sidebar$SidebarLink, {
                                children: Utils$ReactHooksTemplate.str("Modules"),
                                to_: "/modules"
                              })
                        }), React.createElement(Antd.Menu.Item, {
                          key: "2",
                          children: React.createElement(Sidebar$SidebarLink, {
                                children: Utils$ReactHooksTemplate.str("Subjects"),
                                to_: "/subjects"
                              })
                        }), React.createElement(Antd.Menu.Item, {
                          key: "3",
                          children: React.createElement(Sidebar$SidebarLink, {
                                children: Utils$ReactHooksTemplate.str("Topics"),
                                to_: "/topics"
                              })
                        }), React.createElement(Antd.Menu.Item, {
                          key: "4",
                          children: React.createElement(Sidebar$SidebarLink, {
                                children: Utils$ReactHooksTemplate.str("Pages"),
                                to_: "/pages"
                              })
                        }), React.createElement(Antd.Menu.Item, {
                          key: "5",
                          children: React.createElement(Sidebar$SidebarLink, {
                                children: Utils$ReactHooksTemplate.str("Notes"),
                                to_: "/notes"
                              })
                        })), React.createElement(Antd.Menu.SubMenu, {
                      children: null,
                      key: "sub2",
                      title: "Tests"
                    }, React.createElement(Antd.Menu.Item, {
                          key: "6",
                          children: React.createElement(Sidebar$SidebarLink, {
                                children: Utils$ReactHooksTemplate.str("Exams"),
                                to_: "/exams"
                              })
                        }), React.createElement(Antd.Menu.Item, {
                          key: "7",
                          children: React.createElement(Sidebar$SidebarLink, {
                                children: Utils$ReactHooksTemplate.str("Cards"),
                                to_: "/cards"
                              })
                        }))));
}

var make = Sidebar;

export {
  SidebarLink ,
  make ,
  
}
/* antd Not a pure module */
