// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$ReactHooksTemplate from "./Link.bs.js";

function str(prim) {
  return prim;
}

function Sidebar(Props) {
  return React.createElement("div", undefined, React.createElement(Link$ReactHooksTemplate.make, {
                  to_: "/modules",
                  children: "Modules"
                }), React.createElement(Link$ReactHooksTemplate.make, {
                  to_: "/subjects",
                  children: "Subjects"
                }), React.createElement(Link$ReactHooksTemplate.make, {
                  to_: "/topics",
                  children: "Topics"
                }), React.createElement(Link$ReactHooksTemplate.make, {
                  to_: "/pages",
                  children: "Pages"
                }), React.createElement(Link$ReactHooksTemplate.make, {
                  to_: "/notes",
                  children: "Notes"
                }));
}

var make = Sidebar;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
