// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Urql from "urql";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as App$ReactHooksTemplate from "./App.bs.js";

import "./tailwind.css"
;

import "antd/dist/antd.css"
;

import 'katex/dist/katex.min.css';
;

var client = Curry._5(ReasonUrql.Client.make, process.env.API_DEV, undefined, undefined, undefined, /* () */0);

ReactDOMRe.renderToElementWithId(React.createElement(Urql.Provider, {
          value: client,
          children: React.createElement(App$ReactHooksTemplate.make, { })
        }), "root");

export {
  client ,
  
}
/*  Not a pure module */
