// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

var push = ReasonReactRouter.push;

function str(prim) {
  return prim;
}

export {
  push ,
  str ,
  
}
/* ReasonReactRouter Not a pure module */
